SELECT b.TITLE as TITLE, b.BOARD_ID as BOARD_ID, p.REPLY_ID as REPLY_ID, p.WRITER_ID as WRITER_ID, p.CONTENTS as CONTENTS, DATE_FORMAT(p.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
    from USED_GOODS_BOARD b, USED_GOODS_REPLY p
    where b.BOARD_ID = p.BOARD_ID and DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
    order by CREATED_DATE, TITLE
